spring:
  application:
    name: config-dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
dbservice:
  dbc: oracle-db its default for all the application

service:
  oracledb: dev profile data comming from externalized config server - 3
  
