spring:
  application:
    name: oder-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


service:
  oracledb: oder-service comming from qa env. that host in external config server 
