spring:
  application:
    name:  Inventory-Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 dbservice:
    db: value fetching dev profile from inventory service sepefic service
