spring:
  application:
    name: inventory-service
server:
  port: 9093

   

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    prefer-ip-address: true
    non-secure-port: ${server.port}    

service:
  oracledb: oder-service comming from dev env. that host in external config server  
