spring:
  application:
    name: INVENTORY-SERVICE
server:
  port: 9093
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  oracledb: oder-service comming from dev env. that host in external config server  
